COPY-LIST-TO-FTRIPLET [function] (FLOATS DESTINATION3F)
FIND-TWO-FTRIPLETS-MIN-MAX [function] (POINT13F
                                                  POINT23F
                                                  OUT-MIN3F
                                                  OUT-MAX3F)
EQUAL-FTRIPLETS? [macro] (FTRIPLET1 FTRIPLET2 &OPTIONAL TOL)
ROTATE-FTRIPLET [function] (TRIPLET ORDER)
FTRIPLET-VALUES     [macro] (FTRIPLET)
UNIT-FTRIPLET       [function] ()
FTRIPLET-VALUES-BIND [macro] (VARS TRIPLETVAR &BODY BODY)
FILL-FTRIPLET-NORMALIZED [macro] (VECTOR3F (X Y Z &OPTIONAL ...) &OPTIONAL
                                  LENGTH ...)
MAKE-FTRIPLET       [function] (&OPTIONAL X Y Z)
FTRIPLET-X          [macro] (FTRIPLET)
FTRIPLET-Y          [macro] (FTRIPLET)
FTRIPLET-Z          [macro] (FTRIPLET)
X-FTRIPLET          [function] ()
Z-FTRIPLET          [function] ()
Y-FTRIPLET          [function] ()
FTRIPLET-VALUES-SETQ [macro] (VARS TRIPLETVAR)
FTRIPLETS-VALUES-BIND [macro] (VARS&TRIPLETS &BODY BODY)
COPY-FTRIPLET       [function] (TRIPLETVAR &OPTIONAL INTO-FVECTOR START)
USING-FTRIPLET      [macro] ((VARS &OPTIONAL INIT &KEY ...) &BODY BODY)
NORMALIZE-FTRIPLET  [function] (VECTOR3F &OPTIONAL LENGTH)
SCALE-FTRIPLET      [macro] (TRIPLETVAR (XS &OPTIONAL YS ZS) &OPTIONAL
                             INTO-TRIPLETVAR)
FTRIPLET-DVALUES-BIND [macro] (VARS TRIPLETVAR &BODY BODY)
FTRIPLET-LIST       [macro] (FTRIPLET)
MOVE-FTRIPLET       [macro] (TRIPLETVAR (DX DY DZ) &OPTIONAL INTO-TRIPLETVAR)
POSITIVE-INFINITE-FTRIPLET [function] ()
FILL-FTRIPLET       [macro] (TRIPLETVAR &REST VARS)
FTRIPLET-OP         [macro] (OPERATION-FORM INTO-TRIPLET)
ORIGIN-FTRIPLET     [function] ()
NEGATIVE-INFINITE-FTRIPLET [function] ()
FTRIPLETS-DVALUES-BIND [macro] (VARS&TRIPLETS &BODY BODY)
NORMALIZE-HFTRIPLET! [macro] (VECTOR4F &OPTIONAL NEW-LENGTH)
MAKE-FTRIPLET! [macro] (&OPTIONAL X Y Z)
FTRIPLET-A    [macro] (FTRIPLET-ORIENTATION)
FTRIPLET-B    [macro] (FTRIPLET-ORIENTATION)
FTRIPLET-C    [macro] (FTRIPLET-ORIENTATION)
*GTEMP-DIR-FTRIPLET* value: #<Vector @ #x20daf46a>
GET-FTRIPLET-MIDPOINT [function] (PT1 PT2 RETURN3F)
FTRIPLET-W    [macro] (FTRIPLET?)

PARSE-FTRIPLET-FROM-STRING [function] (STRING
                                             RETURN3F
                                             &OPTIONAL
                                             DEFAULT-VALUE
                                             ...)
GEN-FTRIPLET  [function] ()
FILL-FTRIPLET-TRANSFORMED [macro] (FTRIPLET MATRIX X &OPTIONAL ...)
MAKE-FTRIPLET-ARRAY [function] (SIZE)

DEALLOCATE-FTRIPLET [function] (TRIPLET)
UNITIZE-FTRIPLET! [macro] (VECTOR3F &OPTIONAL NEW-SUM)
FILL-MODIFIED-FTRIPLET [macro] (TRIPLETVAR OPS&ARGS)
MODIFY-FTRIPLET [macro] (TRIPLETVAR OPS&VALUES &OPTIONAL INTO-TRIPLETVAR)
ALLOCATE-FTRIPLET [function] (&OPTIONAL INIT)
NORMALIZE-FTRIPLET! [macro] (VECTOR3F &OPTIONAL NEW-LENGTH)

ENSURE-FTRIPLETS [macro] (&REST VARS)
*GTEMP-LOC-FTRIPLET* value: #<Vector @ #x20daf122>
*TEMP-FTRIPLET-ARRAY* value: #<Vector @ #x2202317a>
FTRIPLETS=    [function] (FTRIPLET1 FTRIPLET2)
ORIGIN-FTRIPLET-P [function] (FTRIPLET)
%READ-FTRIPLET! [macro] ((&OPTIONAL STREAM-VAR) FTRIPLET)

MAKE-FTRIPLET-2D-ARRAY [function] (ARRAY)
FTRIPLETS-EQUAL [function] (FTRIPLET1 FTRIPLET2)
FILL-FTRIPLET-CAREFULLY [macro] (TRIPLETVAR &REST VARS)
AVERAGE-OF-FTRIPLET-LIST [function] (LL RETURN3F)
*ALTER-TEMP-FTRIPLET* value: #<Vector @ #x205adc02>
:RELATIVE-FTRIPLET  value: :RELATIVE-FTRIPLET
:NRELATIVE-FTRIPLET-ITEM value: :NRELATIVE-FTRIPLET-ITEM
:NRELATIVE-FTRIPLET value: :NRELATIVE-FTRIPLET
:SF-FTRIPLET-ITEM   value: :SF-FTRIPLET-ITEM
:DECIMAL-FTRIPLET-ITEM value: :DECIMAL-FTRIPLET-ITEM
:RELATIVE-FTRIPLET-ITEM value: :RELATIVE-FTRIPLET-ITEM
NSYS::%IO-WRITE-GEO-FTRIPLET [function] (C-STREAM
                                         NEWLINE
                                         INDENT
                                         INDEX-WIDTH
                                         ...)
NSYS:IO-READ-FTRIPLET [function] (C-STREAM FTRIPLET)
NSYS:IO-WRITE-GEO-FTRIPLET [function] (C-STREAM NEWLINE INDENT INDEX-WIDTH ...)
NSYS:IO-WRITE-FTRIPLET [function] (C-STREAM FTRIPLET)
NSYS:IO-WRITE-BINARY-FTRIPLET [function] (C-STREAM VECTOR &KEY EOF-ERROR-P ...)
NSYS:IO-READ-BINARY-FTRIPLET [function] (C-STREAM VECTOR SWAP &KEY ...)
NSYS-I::%%IO-READ-BINARY-FTRIPLET [function] (C-STREAM FTRIPLET SWAP)
NSYS-I::%IO-WRITE-BINARY-FTRIPLET [function] (C-STREAM FTRIPLET)
NSYS-I::%IO-READ-BINARY-FTRIPLET [function] (C-STREAM FTRIPLET SWAP)

SIM-I::*TEMP-ILI1-FTRIPLET*
SIM-I::*TEMP-ILI2-FTRIPLET*
SIM-I::NEW-HAIR-FTRIPLETS
SIM-I::*TEMP2-TVOTR-FTRIPLET* value: #<Vector @ #x227c7222>
SIM-I::ENSURE-HELIX-ARRAY-OF-FTRIPLETS [function] (NO-OF-NODES-IN-HAIR)
SIM-I::FTRIPLET-SLOTS

